/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GMAIL_APP_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GMAIL_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "portafolio-ventulab": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}